// <auto-generated />
using System;
using Electric_Meter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electric_Meter.Migrations
{
    [DbContext(typeof(PowerTempWatchContext))]
    [Migration("20251203063144_sss")]
    partial class sss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electric_Meter.Dto.DailyConsumptionDTO", b =>
                {
                    b.Property<double>("TotalDailyConsumption")
                        .HasColumnType("float");

                    b.Property<DateTime>("dayData")
                        .HasColumnType("datetime2");

                    b.ToTable("DailyConsumptionDTO");
                });

            modelBuilder.Entity("Electric_Meter.Dto.LatestSensorByDeviceYear", b =>
                {
                    b.Property<double>("TotalValue")
                        .HasColumnType("float");

                    b.Property<string>("device_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.ToTable("LatestSensorByDeviceYear");
                });

            modelBuilder.Entity("Electric_Meter.Dto.LatestSensorDataDTO", b =>
                {
                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Electric_Meter.Dto.TotalConsumptionPercentageDeviceDTO", b =>
                {
                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<double>("TotalConsumption")
                        .HasColumnType("float");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.ToTable("TotalConsumptionPercentageDeviceDTO");
                });

            modelBuilder.Entity("Electric_Meter.Models.ActiveType", b =>
                {
                    b.Property<int>("activeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("activeid");

                    b.ToTable("ActiveType");
                });

            modelBuilder.Entity("Electric_Meter.Models.Codetype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codetypeid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Codetype");
                });

            modelBuilder.Entity("Electric_Meter.Models.Controlcode", b =>
                {
                    b.Property<int>("codeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codeid"));

                    b.Property<int>("activeid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codetypeid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("factor")
                        .HasColumnType("float");

                    b.Property<decimal?>("high")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ifcal")
                        .HasColumnType("int");

                    b.Property<int?>("ifshow")
                        .HasColumnType("int");

                    b.Property<decimal?>("low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("typeid")
                        .HasColumnType("int");

                    b.HasKey("codeid");

                    b.ToTable("controlcode");
                });

            modelBuilder.Entity("Electric_Meter.Models.Device", b =>
                {
                    b.Property<int>("devid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("devid"));

                    b.Property<int>("activeid")
                        .HasColumnType("int");

                    b.Property<int>("ifshow")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.HasKey("devid");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("Electric_Meter.Models.SensorData", b =>
                {
                    b.Property<int>("logid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logid"));

                    b.Property<int>("codeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime2");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("logid");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Electric_Meter.Models.SensorType", b =>
                {
                    b.Property<int>("typeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("typeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeid");

                    b.ToTable("SensorType");
                });
#pragma warning restore 612, 618
        }
    }
}
