// <auto-generated />
using System;
using Electric_Meter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electric_Meter.Migrations
{
    [DbContext(typeof(PowerTempWatchContext))]
    partial class PowerTempWatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electric_Meter.Models.ActiveType", b =>
                {
                    b.Property<int>("activeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("activeid");

                    b.ToTable("ActiveType");
                });

            modelBuilder.Entity("Electric_Meter.Models.Controlcode", b =>
                {
                    b.Property<int>("codeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codeid"));

                    b.Property<int>("activeid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codetypeid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("factor")
                        .HasColumnType("float");

                    b.Property<decimal?>("high")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ifcal")
                        .HasColumnType("int");

                    b.Property<int?>("ifshow")
                        .HasColumnType("int");

                    b.Property<decimal?>("low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("typeid")
                        .HasColumnType("int");

                    b.HasKey("codeid");

                    b.ToTable("controlcode");
                });

            modelBuilder.Entity("Electric_Meter.Models.Device", b =>
                {
                    b.Property<int>("devid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("devid"));

                    b.Property<int>("activeid")
                        .HasColumnType("int");

                    b.Property<int>("address")
                        .HasColumnType("int");

                    b.Property<string>("assembling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("baudrate")
                        .HasColumnType("int");

                    b.Property<int>("ifshow")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.HasKey("devid");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("Electric_Meter.Models.DvElectricDataTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Exp")
                        .HasColumnType("float");

                    b.Property<double?>("Ia")
                        .HasColumnType("float");

                    b.Property<double?>("Ib")
                        .HasColumnType("float");

                    b.Property<double?>("Ic")
                        .HasColumnType("float");

                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.Property<double?>("Imp")
                        .HasColumnType("float");

                    b.Property<double?>("Pa")
                        .HasColumnType("float");

                    b.Property<double?>("Pb")
                        .HasColumnType("float");

                    b.Property<double?>("Pc")
                        .HasColumnType("float");

                    b.Property<double?>("Pt")
                        .HasColumnType("float");

                    b.Property<double?>("TotalElectric")
                        .HasColumnType("float");

                    b.Property<double?>("Ua")
                        .HasColumnType("float");

                    b.Property<double?>("Ub")
                        .HasColumnType("float");

                    b.Property<double?>("Uc")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dv_ElectricDataTemp", (string)null);
                });

            modelBuilder.Entity("Electric_Meter.Models.DvFactoryAssembling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assembling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dv_FactoryAddress_Configs");
                });

            modelBuilder.Entity("Electric_Meter.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<int>("Baudrate")
                        .HasColumnType("int");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dv_Machine");
                });

            modelBuilder.Entity("Electric_Meter.Models.SensorData", b =>
                {
                    b.Property<int>("logid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logid"));

                    b.Property<int>("codeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime2");

                    b.Property<int>("devid")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("logid");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Electric_Meter.Models.SensorType", b =>
                {
                    b.Property<int>("typeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("typeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeid");

                    b.ToTable("SensorType");
                });
#pragma warning restore 612, 618
        }
    }
}
